export type NinhBinhAction =
  | 'NB_BD_MEET_BQL'
  | 'NB_BD_INSPECT_BOX'
  | 'NB_BD_RESOLVE_LIVESTREAM'
  | 'NB_BD_PUBLISH_RULES'
  | 'NB_CP_START_PATROL'
  | 'NB_CP_DISARM_TRAP'
  | 'NB_CP_RESCUE_ANIMAL'
  | 'NB_CP_SECURE_TIMBER'
  | 'NB_TC_MEET_BOATMAN'
  | 'NB_TC_POST_PRICES'
  | 'NB_TC_EQUIP_LIFEJACKETS'
  | 'NB_TC_DISPATCH_BOATS';
