export type NgheAnAction =
  | 'NA_CH_MEET_HOA'
  | 'NA_CH_MEET_TUAN'
  | 'NA_CH_MEASURE_BOUNDARY'
  | 'NA_CH_SIGN_COMMITMENT'
  | 'NA_LD_INTERVIEW_VICTIM'
  | 'NA_LD_ASK_MARKET'
  | 'NA_LD_BLOCK_SHORTCUT'
  | 'NA_LD_CAPTURE_SUSPECT'
  | 'NA_QK_CALM_CROWD'
  | 'NA_QK_INSPECT_CABINET'
  | 'NA_QK_INSPECT_WINDOW'
  | 'NA_QK_INTERROGATE'
  | 'NA_QK_SOLVE_CASE';
