export type ThanhHoaAction =
  | 'TH_NM_MEET_DISPUTE'
  | 'TH_NM_INSPECT_SHOP_C'
  | 'TH_NM_COLLECT_KIT'
  | 'TH_NM_RESOLVE_DISPUTE'
  | 'TH_DR_APPROACH_SCENE'
  | 'TH_DR_SUBDUE_GUARD'
  | 'TH_DR_BLOCK_ESCAPE'
  | 'TH_DR_HANDOVER_EVIDENCE'
  | 'TH_VT_MEET_BRIBE'
  | 'TH_VT_RECORD_EVIDENCE'
  | 'TH_VT_REJECT_ROUGH'
  | 'TH_VT_ACCEPT_BRIBE'
  | 'TH_VT_TRIGGER_ALARM';
