export type HaiPhongAction =
  | 'HP_FD_MEET_HOA'
  | 'HP_FD_SETUP_SIDEWALK'
  | 'HP_FD_ORGANIZE_PARKING'
  | 'HP_FD_POST_PRICES'
  | 'HP_CL_INSPECT_FURNACE'
  | 'HP_CL_TAKE_SAMPLE'
  | 'HP_CL_CHECK_FILTER'
  | 'HP_CL_SIGN_DOSSIER'
  | 'HP_DS_MEET_RESIDENTS'
  | 'HP_DS_POST_PLANNING'
  | 'HP_DS_RESOLVE_COMPENSATION'
  | 'HP_DS_SECURE_EXCAVATOR';
