export type QuangNinhAction =
  | 'QN_TR_MEET_HOANG'
  | 'QN_TR_PEEL_FLIERS'
  | 'QN_TR_DIGITAL_GUIDE'
  | 'QN_TR_PUBLISH_BOARD'
  | 'QN_CT_INSPECT_SITE'
  | 'QN_CT_CHECK_TRUCKS'
  | 'QN_CT_MONITOR_WATER'
  | 'QN_CT_SIGN_COMMITMENT'
  | 'QN_TX_DISCOVER_DEPOT'
  | 'QN_TX_INSPECT_BARGE'
  | 'QN_TX_SEAL_VIOLATION'
  | 'QN_TX_SECURE_BRIDGE';
